### ISSUE TITLE
Integrate JHipster JWT authentication

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster-svelte#49]
Current generator code supports session authentication type. This issue is a placeholder to track integration with JWT authentication type

**Comment by windbender** [comment]
I created a few snippets that might be useful in this direction.  Specifically integration of  fetch-interceptor so that 

a)  JWT response from the login stored in session Store.

and

b) JWT is applied as bearer token header to those fetch requests going to JWT.

It's lacking a centralized interceptor.

it's lacking conversion to .ejs as a generator would require.

**Comment by vishal423** [comment]
I missed this conversation. Feel free to raise a PR with whatever you have. As far as conversion to `.ejs` is concerned, that's fairly simple. To start, you can include files at the appropriate location and add the `.ejs` suffix in the filename

**Comment by vishal423** [comment]
@windbender, Let me know if you would like to contribute the implementation.
